apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-python-deployment
  labels:
    app: docker-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-python
  template:
    metadata:
      labels:
        app: docker-python
    spec:
      containers:
      - name: docker-python
        image: dajari1/testingimg
        ports:
        - containerPort: 5007
